# All files starts with: apiVersion, kind, and metadata fields.
# Order : Service > Deployment/ReplicaSet
# Labels: app: my-app, tier: front-end, phase: test, deployment: v3

apiVersion: v1 # Las versiones parecen ser una locura
kind: Service
metadata:
  name: hello-service
  labels:
    app: hello
spec:
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: hello
---
apiVersion: apps/v1beta2 # Las versiones parecen ser una locura
kind: Deployment
metadata:
  name: hello-deployment
  labels:
    app: hello
spec:
  replicas: 3
  # strategy:
  #   type: RollingUpdate
  selector:
    matchLabels:
      app: hello
  template:
    metadata:
      labels:
        app: hello
    spec:
      containers:
      - name: hello
        image: nginxdemos/hello:plain-text
        # imagePullPolicy: Always
        ports:
        - containerPort: 80
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: hello-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: hello.155.210.158.159.xip.io
    http:
      paths:
      - backend:
          serviceName: hello-service
          servicePort: 80
