apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    certmanager.k8s.io/cluster-issuer: global-issuer
  name: redis
spec:
  rules:
    - host: {}
      http:
        paths:
          - backend:
              serviceName: redis-master
              servicePort: 6379
  tls:
    - hosts:
        - {}
      secretName: redis-tls
