apiVersion: v1
kind: Namespace
metadata:
  name: cert-manager-test
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    certmanager.k8s.io/cluster-issuer: global-issuer
  name: test
  namespace: cert-manager-test
spec:
  rules:
    - host: $HOST
      http:
        paths:
          - backend:
              serviceName: invent
              servicePort: 80
  tls:
    - hosts:
        - $HOST
      secretName: test-tls
